package com.irlink.meritz.ocx.wireless

object IrWirelessMapKey {

    const val KEY: String = "key"
    const val MESSAGE: String = "message"

    const val MSG: String = "msg"
    const val TYPE: String = "type"
    const val CODE: String = "code"
    const val PATH: String = "path"
    const val STATE: String = "state"
    const val LEVEL: String = "level"
    const val VOLUME: String = "volume"
    const val NUMBER: String = "number"
    const val CUS_TEL_NO: String = "cusTelNo"
    const val POSTFIX: String = "postfix"
    const val FILE_NAME: String = "filename"
    const val LOCAL_FILE_NAME: String = "localFileName"
    const val SERVER_FILE_NAME: String = "serverFileName"
    const val SERVER_URL: String = "serverURL"
    const val FILE_SAVE_PATH: String = "fileSavePath"
    const val REMOTE_NUMBERS: String = "remotenumbers"
    const val CONTENT: String = "content"
    const val PARTS: String = "parts"
    const val EXTERNAL_KEY: String = "externalkey"
    const val RESULT_CODE: String = "resultCode"

    const val N_USE: String = "nUse"
    const val N_MODE: String = "nMode"
    const val N_SORT: String = "nSort"
    const val N_FLAG: String = "nFlag"
    const val N_BELL: String = "nBell"
    const val N_RESULT: String = "nResult"
    const val N_CONN_FLAG: String = "nConnFlag"
    const val N_CALL_FLAG: String = "nCallFlag"
    const val N_HOOK_FLAG: String = "nHookFlag"
    const val N_START_END: String = "nStartEnd"
    const val N_LIMIT_FILE_SIZE: String = "nLimitFileSize"

    const val SZ_CNT: String = "szCnt"
    const val SZ_URL: String = "szUrl"
    const val SZ_DATE: String = "szDate"
    const val SZ_PATH: String = "szPath"
    const val SZ_STATE: String = "szState"
    const val SZ_TITLE: String = "szTitle"
    const val SZ_EXTRA: String = "szExtra"
    const val SZ_CONTENT: String = "szContent"
    const val SZ_PB_LIST: String = "szPBList"
    const val SZ_CALL_INFO: String = "szCallInfo"
    const val SZ_FILE_NAME: String = "szFileName"
    const val SZ_FILE_LIST: String = "szFileList"
    const val SZ_SEND_NUMBER: String = "szSendNumber"
    const val SZ_RECV_NUMBER: String = "szRecvNumber"

}